import { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import Link from "next/link";
import NavigationBar from "../../components/Layout/mobile-tool-bar";
import Product from "../../components/Products/product";

const Products: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Product />
      <Product />
      <Product />
      <Product />
      <Product />
    </div>
  );
};

export default Products;
