import { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import Product from "../../components/Products/product";
import { getAllProducts } from "../../services/productService";

export const getStaticProps = async () => {
  const data = await getAllProducts();
  return {
    props: { products: data },
  };
};

const Products = ({ products }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {products.map((product) => (
        <div key={product.id}>{product.name}</div>
      ))}
      <Product />
      <Product />
      <Product />
      <Product />
      <Product />
    </div>
  );
};

// class Products extends Component {
//   products = [];

//   getAllProducts = () => {
//     const data = getAllProducts().then((response) => {
//       this.products.push(response);
//       console.log(this.products);
//     });
//   };
//   render() {
//     return <div>hello {this.products}!</div>;
//   }
// }

export default Products;
